version: "3.8"

services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=jira_clone
    ports:
      # Outside:Inside
      - 5432:5432
    networks:
      - shared-jira-network
    volumes:
      # localpath:containerpath
      - ./postgres-db:/var/lib/postgresql/data

  api:
    container_name: jira_api
    restart: unless-stopped
    image: jira_api:1.0.0
    build:
      context: api
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-jira-network
    depends_on:
      - postgres

  client:
    container_name: jira_client
    restart: unless-stopped
    image: jira_client:1.0.0
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    networks:
      - shared-jira-network
    depends_on:
      - api

networks:
  shared-jira-network:
